services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - local-network

volumes:
  postgres:

networks:
  local-network:
    external: true
